version: '3.8'

services:
  web:
    image: bryangerlach/family_chore_app:latest
    container_name: family_chore_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /opt/appdata/family_chore_app/db:/app/db
      - /opt/appdata/family_chore_app/staticfiles:/app/staticfiles
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-change-this-to-a-secure-random-key-in-production