# Generated by Django 5.0.3 on 2026-09-22 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_type', models.CharField(choices=[('child', 'Child'), ('parent', 'Parent')], default='child', max_length=10)),
                ('pin', models.CharField(blank=True, help_text='4-digit PIN for kids', max_length=4, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting Approval'), ('approved', 'Approved / Completed')], default='pending', max_length=10)),
                ('child', models.ForeignKey(limit_choices_to={'user_type': 'child'}, on_delete=django.db.models.deletion.CASCADE, to='chores.profile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.task')),
            ],
        ),
    ]
