# Generated by Django 5.0.3 on 2026-09-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emoji',
            field=models.CharField(default='👦', help_text='Profile icon emoji', max_length=10),
        ),
        migrations.AlterField(
            model_name='dailytaskstatus',
            name='date',
            field=models.DateField(),
        ),
    ]
