# Generated by Django 5.0.3 on 2026-09-24 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_profile_emoji_alter_dailytaskstatus_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('star_cost', models.PositiveIntegerField(default=1, help_text='Stars required to redeem')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task_images/'),
        ),
        migrations.AddField(
            model_name='task',
            name='star_value',
            field=models.PositiveIntegerField(default=1, help_text='Stars earned when approved'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RedemptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled', models.BooleanField(default=True, help_text='Mark false if parent needs to approve/hand out physical reward')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='chores.profile')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.reward')),
            ],
        ),
    ]
