# Generated by Django 5.0.3 on 2026-09-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_reward_task_image_task_star_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redemptionlog',
            name='fulfilled',
        ),
        migrations.AddField(
            model_name='redemptionlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10),
        ),
    ]
