# Generated by Django 5.0.3 on 2026-09-24 02:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_remove_redemptionlog_fulfilled_redemptionlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytaskstatus',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.profile'),
        ),
        migrations.AlterField(
            model_name='dailytaskstatus',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='dailytaskstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting for Approval'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
