# Generated by Django 5.0.3 on 2026-09-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0005_alter_dailytaskstatus_child_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allowed_days',
            field=models.CharField(default='0,1,2,3,4,5,6', help_text='Comma-separated days: 0=Sun, 1=Mon, 2=Tue, 3=Wed, 4=Thu, 5=Fri, 6=Sat', max_length=20),
        ),
    ]
