# Generated by Django 5.0.3 on 2026-09-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0006_task_allowed_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='is_one_time',
            field=models.BooleanField(default=False, help_text='Check if this reward can only be claimed once per child'),
        ),
    ]
