# Generated by Django 5.0.3 on 2026-09-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0007_reward_is_one_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('recurring', 'Recurring (Unlimited)'), ('one_time', 'One-Time Only (Never again once claimed)'), ('weekly', 'Once Per Week (Resets every Sunday)')], default='recurring', max_length=20),
        ),
        migrations.AlterField(
            model_name='reward',
            name='is_one_time',
            field=models.BooleanField(default=False),
        ),
    ]
