# Generated by Django 5.0.3 on 2026-09-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0008_reward_reward_type_alter_reward_is_one_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='star_cost',
            field=models.IntegerField(default=0, help_text='Stars required to redeem'),
        ),
    ]
