# Generated by Django 5.0.3 on 2026-09-25 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0009_alter_reward_star_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinStoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., 1 Star Point', max_length=100)),
                ('coin_cost', models.PositiveIntegerField(default=10)),
                ('star_value_granted', models.PositiveIntegerField(default=0, help_text='Stars granted when bought')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('math', 'Math Problem'), ('reading', 'Reading Comprehension')], default='math', max_length=20)),
                ('passage', models.TextField(blank=True, help_text='For reading: the story or paragraph', null=True)),
                ('question_text', models.TextField(help_text='The question to answer')),
                ('option_a', models.CharField(max_length=100)),
                ('option_b', models.CharField(max_length=100)),
                ('option_c', models.CharField(blank=True, max_length=100, null=True)),
                ('option_d', models.CharField(blank=True, max_length=100, null=True)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('coin_reward', models.PositiveIntegerField(default=5, help_text='Coins earned for correct answer')),
            ],
        ),
        migrations.CreateModel(
            name='CoinLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive for earned, negative for spent')),
                ('reason', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to='chores.profile')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_date', models.DateField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.quizquestion')),
            ],
            options={
                'unique_together': {('child', 'question', 'solved_date')},
            },
        ),
    ]
