# Generated by Django 5.0.3 on 2026-09-25 01:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0010_coinstoreitem_quizquestion_coinledger_quizattempt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='solved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='solved_date',
        ),
    ]
