# Generated by Django 5.0.3 on 2026-09-25 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0011_alter_quizattempt_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizWrongAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.quizquestion')),
            ],
        ),
    ]
