# Generated by Django 5.0.3 on 2026-09-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0012_quizwrongattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizwrongattempt',
            name='option_chosen',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
