# Generated by Django 5.0.3 on 2026-09-25 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0013_quizwrongattempt_option_chosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='chores.profile'),
        ),
    ]
