# Generated by Django 5.0.3 on 2026-09-26 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0014_quizquestion_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemptionlog',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.profile'),
        ),
        migrations.AlterField(
            model_name='redemptionlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='StarLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.profile')),
            ],
        ),
    ]
