# Generated by Django 5.0.3 on 2026-09-28 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0015_alter_redemptionlog_child_alter_redemptionlog_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcadeHighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_key', models.CharField(max_length=50)),
                ('game_title', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcade_high_scores', to='chores.profile')),
            ],
            options={
                'unique_together': {('child', 'game_key')},
            },
        ),
    ]
