# Generated by Django 5.0.3 on 2026-09-29 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0016_arcadehighscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='StarBuddy', max_length=50)),
                ('species', models.CharField(default='Pixel Dragon', max_length=30)),
                ('hunger', models.IntegerField(default=100)),
                ('happiness', models.IntegerField(default=100)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='chores.profile')),
            ],
        ),
    ]
