# Generated by Django 5.0.3 on 2026-09-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0017_virtualpet'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualpet',
            name='poop_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='virtualpet',
            name='species',
            field=models.CharField(default='Pixel Critter', max_length=30),
        ),
    ]
