# Generated by Django 5.0.3 on 2026-09-29 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0018_virtualpet_poop_count_alter_virtualpet_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL (Home Assistant, Discord, ntfy.sh, etc.)', max_length=500, null=True)),
                ('notify_chore_waiting', models.BooleanField(default=True, help_text='Notify when a child requests chore approval')),
                ('notify_reward_requested', models.BooleanField(default=True, help_text='Notify when a child requests a reward')),
                ('notify_quiz_completed', models.BooleanField(default=False, help_text='Notify on quiz activity')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_config', to='chores.profile')),
            ],
        ),
    ]
