# Generated by Django 5.0.3 on 2026-10-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0019_parentnotificationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentnotificationconfig',
            name='show_shared_leaderboard',
            field=models.BooleanField(default=True, help_text="Allow children to see each other's scores in the arcade"),
        ),
    ]
